// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCMwT507-5699hnOhn0z9GTteKz2J2Nd0',
    appId: '1:711264923392:web:162f6b3b2187b1f8430de5',
    messagingSenderId: '711264923392',
    projectId: 'flutterchatapp-c5b63',
    authDomain: 'flutterchatapp-c5b63.firebaseapp.com',
    storageBucket: 'flutterchatapp-c5b63.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGTnDq8u3U4iL-RBhW5rQKgTZOTJkXGSA',
    appId: '1:711264923392:android:be93b44743c70762430de5',
    messagingSenderId: '711264923392',
    projectId: 'flutterchatapp-c5b63',
    storageBucket: 'flutterchatapp-c5b63.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzxoDwWA9TZa7-GJOmKKA3rs0UpwR7pHY',
    appId: '1:711264923392:ios:ef5c268fe2f12164430de5',
    messagingSenderId: '711264923392',
    projectId: 'flutterchatapp-c5b63',
    storageBucket: 'flutterchatapp-c5b63.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzxoDwWA9TZa7-GJOmKKA3rs0UpwR7pHY',
    appId: '1:711264923392:ios:ef5c268fe2f12164430de5',
    messagingSenderId: '711264923392',
    projectId: 'flutterchatapp-c5b63',
    storageBucket: 'flutterchatapp-c5b63.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCMwT507-5699hnOhn0z9GTteKz2J2Nd0',
    appId: '1:711264923392:web:a012a959156bb765430de5',
    messagingSenderId: '711264923392',
    projectId: 'flutterchatapp-c5b63',
    authDomain: 'flutterchatapp-c5b63.firebaseapp.com',
    storageBucket: 'flutterchatapp-c5b63.appspot.com',
  );
}
